fix #42 by adding prepack script
keep-starknet-strange/abi-wan-kanabi pull request #43
Opened 2023-10-13 15:52 UTC by adrian-gierakowski

and some tsconfig settings

this ensures the content of nmp package don't break due to consumers using different TypeScript config

2023-10-18 09:30 UTC, haroune-mohammedi approved these changes
LGTM

2023-10-18 10:10 UTC, tabaktoni approved these changes
Lgtm

2023-10-18 11:25 UTC, haroune-mohammedi requested changes
I tested it against `starknet.js` and it fails with:

```
../abi-wan-kanabi/dist/kanabi.d.ts:1:101 - error TS2307: Cannot find module './starknet' or its corresponding type declarations.

1 import { BigNumberish, CallOptions, Calldata, InvokeFunctionResponse, InvokeOptions, Uint256 } from './starknet';
                                                                                                      ~~~~~~~~~~~~
Found 1 error in ../abi-wan-kanabi/dist/kanabi.d.ts:1
```

@adrian-gierakowski  you have to make sure the `starknet.d.ts` file is included in the `dist` folder

2023-10-18 17:03 UTC, adrian-gierakowski commented
@haroune-mohammedi should be fixed now

2024-01-12 10:33 UTC, haroune-mohammedi commented
Fixed by #56

2024-01-12 10:33 UTC, closed without merging